# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EYgibbs <- function(N, p, Y, Z, se, sp, na, GI) {
    .Call(`_aenetgt_EYgibbs`, N, p, Y, Z, se, sp, na, GI)
}

EYiYjgibbs_slow <- function(N, p, Y, Z, se, sp, na, GI) {
    .Call(`_aenetgt_EYiYjgibbs_slow`, N, p, Y, Z, se, sp, na, GI)
}

CovYiYjgibbs <- function(N, p, Y, Z, W, se, sp, EY, na, GI) {
    .Call(`_aenetgt_CovYiYjgibbs`, N, p, Y, Z, W, se, sp, EY, na, GI)
}

logistic_enet <- function(Yr, Xr, lambda, gammar, theta, binitr, delta) {
    .Call(`_aenetgt_logistic_enet`, Yr, Xr, lambda, gammar, theta, binitr, delta)
}

llj_array <- function(Zjr, Zjc, Yji, whichjretest, pxji, Se, Sp, B) {
    .Call(`_aenetgt_llj_array`, Zjr, Zjc, Yji, whichjretest, pxji, Se, Sp, B)
}

#' Generate all possible sequences of 0s and 1s of a given length
#' @param a the length of the sequences.
#' @return a matrix containing in its rows the sequences of 0s and 1s.
all_binary_sequences <- function(a) {
    .Call(`_aenetgt_all_binary_sequences`, a)
}

#' Computes conditional expectations of individual disease statuses for individual, master pool, or Dorfman testing
#'   
#' @param Z Group testing output from one of the functions \code{individual.assay.gen}, \code{masterpool.assay.gen}, \code{dorfman.assay.gen}.
#' @param Y Group testing output from one of the functions \code{individual.assay.gen}, \code{masterpool.assay.gen}, \code{dorfman.assay.gen}.
#' @param X Design matrix with first column a column of 1s.
#' @param b Parameter values at which to compute the conditional expectations.
#' @param Se A vector of testing sensitivities of length \code{max(Z[,3])}.
#' @param Sp A vector of testing specificities of length \code{max(Z[,3])}.
#' @return The vector of conditional expectations.
#' 
#' This function computes the conditional expectations of each individual disease status, conditional on the observed assay data and the diseasestatuses of all other individuals.
#' 
#' @examples
#' # generate individual covariate values and disease statuses
#' N <- 100
#' data <- model1(N)
#' X <- data$X
#' Y.true <- data$Yi
#' Se <- c(.95,.92) # set master pool and individual assay sensitivity
#' Sp <- c(.97,.98) # set master pool and individual assay specificity
#' cj <- 4 # set size of master pools
#' # subject individuals to Dorfman testing
#' assay.data <- dorfman.assay.gen(Y.true,Se,Sp,cj)
#' Z <- assay.data$Z
#' Y <- assay.data$Y
#' b <- data$b
#'   
#' EY <- EYexact(Z,Y,X,b,Se,Sp)
EYexact <- function(Z, Y, X, b, Se, Sp) {
    .Call(`_aenetgt_EYexact`, Z, Y, X, b, Se, Sp)
}

